// Auto-generated by ata-validator — do not edit
'use strict';
const boolFn = function(d) {
  if(!((typeof d==='object'&&d!==null&&!Array.isArray(d))))return false
  const{"id":_h0,"name":_h1,"email":_h2,"active":_h3}=d
  if(_h0===undefined||_h1===undefined||_h2===undefined||_h3===undefined)return false
  if(!(Number.isInteger(_h0)))return false
  if(_h0<1)return false
  if(!(typeof _h1==='string'))return false
  if(_h1.length<1)return false
  if(!(typeof _h2==='string'))return false
  {const _at=_h2.indexOf('@');if(_at<=0||_at>=_h2.length-1||_h2.indexOf('.',_at)<=_at+1)return false}
  if(!(typeof _h3==='boolean'))return false
  {const _o4=d["f476"];if(_o4!==undefined){
  if(!(typeof _o4==='string'))return false
  }}
  return true
};
const hybridFactory = function(R, E) {
  return function(d) {
    if(!((typeof d==='object'&&d!==null&&!Array.isArray(d))))return E(d)
  const{"id":_h0,"name":_h1,"email":_h2,"active":_h3}=d
  if(_h0===undefined||_h1===undefined||_h2===undefined||_h3===undefined)return E(d)
  if(!(Number.isInteger(_h0)))return E(d)
  if(_h0<1)return E(d)
  if(!(typeof _h1==='string'))return E(d)
  if(_h1.length<1)return E(d)
  if(!(typeof _h2==='string'))return E(d)
  {const _at=_h2.indexOf('@');if(_at<=0||_at>=_h2.length-1||_h2.indexOf('.',_at)<=_at+1)return E(d)}
  if(!(typeof _h3==='boolean'))return E(d)
  {const _o4=d["f476"];if(_o4!==undefined){
  if(!(typeof _o4==='string'))return E(d)
  }}
  return R
  };
};
const errFn = function(d, _all) {
  const _e=[];
  if(!((typeof d==='object'&&d!==null&&!Array.isArray(d)))){_e.push({code:'type_mismatch',path:"",message:'expected object'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&!("id" in d)){_e.push({code:'required_missing',path:'/id',message:'missing required: id'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&!("name" in d)){_e.push({code:'required_missing',path:'/name',message:'missing required: name'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&!("email" in d)){_e.push({code:'required_missing',path:'/email',message:'missing required: email'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&!("active" in d)){_e.push({code:'required_missing',path:'/active',message:'missing required: active'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&"id" in d){
  if(!(Number.isInteger(d["id"]))){_e.push({code:'type_mismatch',path:'/id',message:'expected integer'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d["id"]==='number'&&d["id"]<1){_e.push({code:'minimum_violation',path:'/id',message:'minimum 1'});if(!_all)return{valid:false,errors:_e}}
  }
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&"name" in d){
  if(!(typeof d["name"]==='string')){_e.push({code:'type_mismatch',path:'/name',message:'expected string'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d["name"]==='string'&&d["name"].length<1){_e.push({code:'min_length_violation',path:'/name',message:'minLength 1'});if(!_all)return{valid:false,errors:_e}}
  }
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&"email" in d){
  if(!(typeof d["email"]==='string')){_e.push({code:'type_mismatch',path:'/email',message:'expected string'});if(!_all)return{valid:false,errors:_e}}
  if(typeof d["email"]==='string'){const _at=d["email"].indexOf('@');if(_at<=0||_at>=d["email"].length-1||d["email"].indexOf('.',_at)<=_at+1){_e.push({code:'format_mismatch',path:'/email',message:'format email'});if(!_all)return{valid:false,errors:_e}}}
  }
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&"active" in d){
  if(!(typeof d["active"]==='boolean')){_e.push({code:'type_mismatch',path:'/active',message:'expected boolean'});if(!_all)return{valid:false,errors:_e}}
  }
  if(typeof d==='object'&&d!==null&&!Array.isArray(d)&&"f476" in d){
  if(!(typeof d["f476"]==='string')){_e.push({code:'type_mismatch',path:'/f476',message:'expected string'});if(!_all)return{valid:false,errors:_e}}
  }
  return{valid:_e.length===0,errors:_e}
};
module.exports = { boolFn, hybridFactory, errFn };
